org: polynize
app: aws-algorand-reach-poc
service: aws-algorand-reach-poc
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
